language: php

sudo: false

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories: $HOME/.composer/cache

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit --testsuite unit
